windows-x86: define __MINGW32__ for JSHTTP (JSImage when Frontend)
Problem: the type is defined in pthreads4w
error C2632: '__int64' followed by '__int64' is illegal
warning C4114: same type qualifier used more than once