windows-x86: change ternary expression to get better casting
Problem: msvc could not find the correct type to convert to pointer or handle type

3>C:\Data\nidium\Nidium\src\Binding/ThreadLocalContext.h(82): error C2446: ':': no conversion from 'const JS::Heap<JSObject *>' to 'nullptr'
3>  C:\Data\nidium\Nidium\src\Binding/ThreadLocalContext.h(82): note: nullptr can only be converted to pointer or handle types