windows-x86: removing an obsolete pthread include
Problem: this include was obsolete, but the pthread include it selve causes problems

Note: remaining problem is:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\stdint.h(20): error C2632: '__int64' followed by '__int64' is illegal [c:\Data\nidium\Nidium\gyp\libnidiumcore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\stdint.h(24): error C2632: '__int64' followed by '__int64' is illegal [c:\Data\nidium\Nidium\gyp\libnidiumcore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(19): error C2589: '__int64': illegal token on right side of '::' [c:\Data\nidium\Nidium\gyp\libnidiumcore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(19): error C2059: syntax error: '::' [c:\Data\nidium\Nidium\gyp\libnidiumcore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(21): error C2589: 'unsigned': illegal token on right side of '::' [c:\Data\nidium\Nidium\gyp\libnidiumcore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(21): error C2059: syntax error: '::' [c:\Data\nidium\Nidium\gyp\libnidiumcore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(39): error C2589: '__int64': illegal token on right side of '::' [c:\Data\nidium\Nidium\gyp\libnidiumcore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(39): error C2059: syntax error: '::' [c:\Data\nidium\Nidium\gyp\libnidiumcore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(41): error C2589: 'unsigned': illegal token on right side of '::' [c:\Data\nidium\Nidium\gyp\libnidiumcore.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\cstdint(41): error C2059: syntax error: '::' [c:\Data\nidium\Nidium\gyp\libnidiumcore.vcxproj]